### ISSUE TITLE
Indexer program stopped at reorganized block

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/darwinia#1633]
At present, it is a guess that it may be related to sql db, and more tests and information are needed to verify it.
The affected services are ponder, thegraph

```

URL: https://rpc.darwinia.network
Request body: {"method":"eth_getLogs","params":[{"blockHash":"0x49aae73c500163ba3ffd3a83596007baa6e75326a8ab847dec4726da781658dd"}]}

Details: unknown block
Version: viem@1.21.3
    at withRetry.delay.count.count (file:///app/node_modules/viem/utils/buildRequest.ts:152:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at attemptRetry (file:///app/node_modules/viem/utils/promise/withRetry.ts:37:22)
caused by: RpcRequestError: RPC Request failed.

URL: https://rpc.darwinia.network
Request body: {"method":"eth_getLogs","params":[{"blockHash":"0x49aae73c500163ba3ffd3a83596007baa6e75326a8ab847dec4726da781658dd"}]}

Details: unknown block
Version: viem@1.21.3
    at request (file:///app/node_modules/viem/clients/transports/http.ts:111:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withRetry.delay.count.count (file:///app/node_modules/viem/utils/buildRequest.ts:129:18)
    at attemptRetry (file:///app/node_modules/viem/utils/promise/withRetry.ts:37:22)
caused by:
8:46:57 AM WARN  realtime   Failed to process 'darwinia' block 4747006

caused by: RpcRequestError: RPC Request failed.

URL: https://rpc.darwinia.network
Request body: {"method":"eth_getLogs","params":[{"blockHash":"0x49aae73c500163ba3ffd3a83596007baa6e75326a8ab847dec4726da781658dd"}]}

Details: unknown block
Version: viem@1.21.3
    at request (file:///app/node_modules/viem/clients/transports/http.ts:111:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withRetry.delay.count.count (file:///app/node_modules/viem/utils/buildRequest.ts:129:18)
    at attemptRetry (file:///app/node_modules/viem/utils/promise/withRetry.ts:37:22)
caused by:
8:46:57 AM WARN  realtime   Retrying 'darwinia' sync after 1 second.
8:48:26 AM WARN  realtime   Detected forked 'darwinia' block at height 4747035
8:48:27 AM WARN  realtime   Reconciled 2-block reorg on 'darwinia' with common ancestor block 4747033
8:49:31 AM WARN  realtime   Detected forked 'darwinia' block at height 4747046



```

**Comment by fewensa** [comment]
use thegraph
Crab index stopped, use sql backend

```
{
  "data": {
    "_meta": {
      "hasIndexingErrors": false,
      "deployment": "QmZrSy6iUhj8a3cgZe4EQh2Ffncq3L2h1sKZD81RU7TQKR",
      "block": {
        "timestamp": null,
        "parentHash": null,
        "number": 4748739,
        "hash": "0x147f916d5499fa10a9c3fa91ea21e5f457a796b57ca266b4bf5f7eaca2f1df73"
      }
    }
  }
}
```

https://crab-scan.darwinia.network/block/0x147f916d5499fa10a9c3fa91ea21e5f457a796b57ca266b4bf5f7eaca2f1df73
