### ISSUE TITLE
Eth Relay: Duplicate header relay shoud fail, but didn't

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#214]
https://icefrog.subscan.io/extrinsic/7242-1
https://icefrog.subscan.io/extrinsic/7335-1

**Comment by HackFisher** [comment]
```
{"message":"start build resetGenesisHeader extrinsic","level":"info"}
2020-03-02 15:17:12             DRR: TypeError: Cannot read property 'account' of undefined
    at SwitchMapSubscriber.project (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/@polkadot/api-derive/balances/account.js:78:150)
    at SwitchMapSubscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/operators/switchMap.js:49:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ReplaySubject.Subject.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/ReplaySubject.js:48:31)
    at ConnectableSubscriber.Subscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:89:26)
    at ConnectableSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
    at DistinctUntilChangedSubscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)
    at DistinctUntilChangedSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
    at CatchSubscriber.Subscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:89:26)
    at CatchSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapSubscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/operators/switchMap.js:89:26)
    at InnerSubscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
{"message":"createTx ErrorTypeError: Cannot read property 'account' of undefined","level":"error"}
```

**Comment by AurevoirXavier** [comment]
> ```
> {"message":"start build resetGenesisHeader extrinsic","level":"info"}
> 2020-03-02 15:17:12             DRR: TypeError: Cannot read property 'account' of undefined
>     at SwitchMapSubscriber.project (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/@polkadot/api-derive/balances/account.js:78:150)
>     at SwitchMapSubscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/operators/switchMap.js:49:27)
>     at SwitchMapSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
>     at ReplaySubject.Subject.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subject.js:60:25)
>     at ReplaySubject.nextInfiniteTimeWindow (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/ReplaySubject.js:48:31)
>     at ConnectableSubscriber.Subscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:89:26)
>     at ConnectableSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
>     at DistinctUntilChangedSubscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)
>     at DistinctUntilChangedSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
>     at CatchSubscriber.Subscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:89:26)
>     at CatchSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
>     at MapSubscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/operators/map.js:55:26)
>     at MapSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
>     at SwitchMapSubscriber.notifyNext (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/operators/switchMap.js:89:26)
>     at InnerSubscriber._next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
>     at InnerSubscriber.Subscriber.next (/Users/denny/github.com/darwinia-network/darwinia-proof-tools/node_modules/rxjs/internal/Subscriber.js:66:18)
> {"message":"createTx ErrorTypeError: Cannot read property 'account' of undefined","level":"error"}
> ```

Due to

Balances to Ring, 93d948e2cc3886c88d284d79f5c2a322193e35a4

**Comment by HackFisher** [comment]
This already been fix. Another issue reported from @WoeOm , saying that after relayer worker get killed, re-calling relay_header will fail for the latest block, but not reproduced for now.

**Comment by HackFisher** [comment]
Fixed in following checking:

```
ensure!(! HeaderInfoOf::get(&header_hash).is_some(), "The header is already known.");
```
