### ISSUE TITLE
Get error log information when starting the Icefrog CentOS client

### ISSUE THREAD

**Issue by flyq** [darwinia-network/darwinia#215]
CentOS 系统，启动时 log 输出：
```shell
~/icefrog/CentOS$ ./darwinia --conf=config.json
2020-01-02 15:10:19 Darwinia IceFrog Node
2020-01-02 15:10:19 Version: 0.4.6-0174b00-x86_64-linux-gnu
2020-01-02 15:10:19   _____                      _       _       
2020-01-02 15:10:19  |  __ \                    (_)     (_)      
2020-01-02 15:10:19  | |  | | __ _ _ ____      ___ _ __  _  __ _ 
2020-01-02 15:10:19  | |  | |/ _` | '__\ \ /\ / / | '_ \| |/ _` |
2020-01-02 15:10:19  | |__| | (_| | |   \ V  V /| | | | | | (_| |
2020-01-02 15:10:19  |_____/ \__,_|_|    \_/\_/ |_|_| |_|_|\__,_|
2020-01-02 15:10:19 Chain specification: Darwinia IceFrog Testnet
2020-01-02 15:10:19 Node name: Flyq
2020-01-02 15:10:19 Roles: "AUTHORITY"
2020-01-02 15:10:19 Initializing Genesis block/state (state: 0x993d…6f53, header-hash: 0xa7de…7c54)
2020-01-02 15:10:19 Loading GRANDPA authority set from genesis on what appears to be first startup.
2020-01-02 15:10:19 Loaded block-time = BabeConfiguration { slot_duration: 3000, epoch_length: 200, c: (1, 4), genesis_authorities: [(Public(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...)), 1), (Public(8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48 (5FHneW46...)), 1)], randomness: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], secondary_slots: true } milliseconds from genesis on first-launch
2020-01-02 15:10:19 Creating empty BABE epoch changes on what appears to be first startup.
2020-01-02 15:10:19 Highest known block at #0
2020-01-02 15:10:19 Local node identity is: QmNbU5KY7Y1P5urTMYHCDzEU8NZddy3fYUh3a3MedfEg5e
2020-01-02 15:10:19 Starting BABE Authorship worker
2020-01-02 15:10:20 Discovered new external address for our node: /ip4/101.132.117.50/tcp/23334/p2p/QmNbU5KY7Y1P5urTMYHCDzEU8NZddy3fYUh3a3MedfEg5e
2020-01-02 15:10:20 New epoch 0 launching at block 0x95ef…e914 (block slot 525978592 >= start slot 525978592).
2020-01-02 15:10:20 Next epoch starts at slot 525978792
2020-01-02 15:10:20 New epoch 1 launching at block 0xacea…baf2 (block slot 525978792 >= start slot 525978792).
2020-01-02 15:10:20 Next epoch starts at slot 525978992
2020-01-02 15:10:20 New epoch 2 launching at block 0x4a0b…1318 (block slot 525978992 >= start slot 525978992).
2020-01-02 15:10:20 Next epoch starts at slot 525979192
2020-01-02 15:10:21 New epoch 3 launching at block 0xfe80…e9e1 (block slot 525979192 >= start slot 525979192).
2020-01-02 15:10:21 Next epoch starts at slot 525979392
2020-01-02 15:10:21 New epoch 4 launching at block 0x1bad…2aa6 (block slot 525979392 >= start slot 525979392).
2020-01-02 15:10:21 Next epoch starts at slot 525979592
2020-01-02 15:10:21 New epoch 5 launching at block 0x433a…042f (block slot 525979592 >= start slot 525979592).
2020-01-02 15:10:21 Next epoch starts at slot 525979792
Hash: given=3636b0c57ee943bced8b0747d4f70aaa60d6018133f0add907a194fbea00e663, expected=8e8058f6f8d9d4ecb4d3a3d942d438d8c22e0827700e092679359d495e38f9bc

====================

Version: 0.4.6-0174b00-x86_64-linux-gnu

stack backtrace:
  26: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/da3629b05f8f1b425a738bfe9fe9aedd47c5417a/src/liballoc/boxed.rs:1015
  29: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/da3629b05f8f1b425a738bfe9fe9aedd47c5417a/src/liballoc/boxed.rs:1015
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  30: start_thread
  31: clone


Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /home/sunbobin/.cargo/git/checkouts/substrate-a7fa553ead635512/d2c4b0d/srml/executive/src/lib.rs:277

This is a bug. Please report it at:

        https://github.com/darwinia-network/darwinia/issues/new
```
最后停止报错，并且同步正常。

下面是我的配置：
```json
{
    "base-path": "/root/icefrog/CentOS/data/",
    "bootnodes": [
        "/ip4/35.234.35.49/tcp/6666/p2p/QmbKSNfeBGYiUiWAcpoeiM3pgAMagbRFXfWdgZ6nrT2koN",
        "/ip4/35.234.35.49/tcp/20222/p2p/QmSEixwSMBLnkcAVSNenBLu1d3DoZfTFTFWE16BYSN4bMB",
        "/ip4/121.199.60.87/tcp/20222/p2p/QmW26ydfXEALbj7Mm67czs4DxgKjyyMDW4ng9xGphSP1zu"
    ],

    "name": "Flyq",
    "validator": true,

    "rpc-external": true,
    "rpc-port": 23332,
    "ws-external": true,
    "ws-port": 23333,
    "rpc-cors": "all",
    "port": 23334
}
```

**Comment by AurevoirXavier** [comment]
dup #213
