### ISSUE TITLE
finalized block is blocked

### ISSUE THREAD

**Issue by flyq** [darwinia-network/darwinia#230]
It runs well somedays ago.
but the finalized blocks is blocked at 115886. It can't be fixed by restart.

env:
```shell
$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
```
client version:
https://github.com/darwinia-network/darwinia/releases/download/v0.4.6/CentOS.tar.gz

config.json:
```json
{
    "base-path": "/root/icefrog/CentOS/data/",
    "bootnodes": [
        "/ip4/35.234.35.49/tcp/6666/p2p/QmY2re382ng8VekYkRipPRAtNFxTnA6UgyiaRE8Jq98Fm6",
        "/ip4/121.199.60.87/tcp/20222/p2p/QmXtQhnKQttAe4JVxDHc6ivmXhqZzGBufjoczo6xSAc8LU",
        "/ip4/94.191.64.39/tcp/20222/p2p/QmcFnM532f3yApiuD9DNqmQjL7XezLU7PPN7BYznXTftj2",
        "/ip4/59.41.200.34/tcp/23334/p2p/QmSNmqD7o4qqoPhAJf4ghnmiWvDL9QZJWmE5KLR4DpA8rZ"
    ],
    "name": "Flyq",
    "validator": true,
    "rpc-external": true,
    "rpc-port": 23332,
    "ws-external": true,
    "ws-port": 23333,
    "rpc-cors": "all",
    "port": 23334
}
```

log:
```shell
2020-01-07 08:45:30 Idle (15 peers), best: #134250 (0x3ff7…ad94), finalized #115886 (0xdd29…1183), ⬇ 6.2kiB/s ⬆ 5.5kiB/s
2020-01-07 08:45:34 Imported #134251 (0x16d0…703c)
2020-01-07 08:45:35 Idle (15 peers), best: #134251 (0x16d0…703c), finalized #115886 (0xdd29…1183), ⬇ 5.2kiB/s ⬆ 4.3kiB/s
2020-01-07 08:45:39 Discovered new external address for our node: /ip4/10.156.1.47/tcp/23334/p2p/QmNbU5KY7Y1P5urTMYHCDzEU8NZddy3fYUh3a3MedfEg5e
2020-01-07 08:45:39 Reorg from #134251,0x16d0…703c to #134251,0x88e1…4d3a, common ancestor #134250,0x3ff7…ad94
2020-01-07 08:45:39 Imported #134251 (0x88e1…4d3a)
2020-01-07 08:45:40 Idle (15 peers), best: #134251 (0x88e1…4d3a), finalized #115886 (0xdd29…1183), ⬇ 8.2kiB/s ⬆ 5.7kiB/s
2020-01-07 08:45:45 Imported #134252 (0xa8f2…02d7)
2020-01-07 08:45:45 Idle (15 peers), best: #134252 (0xa8f2…02d7), finalized #115886 (0xdd29…1183), ⬇ 7.1kiB/s ⬆ 5.3kiB/s
^Cpure virtual method called
terminate called without an active exception
Aborted
134 root@iZuf679ganic8z8whgaxhtZ:~/icefrog/CentOS$ ^C
130 root@iZuf679ganic8z8whgaxhtZ:~/icefrog/CentOS$ ./darwinia --conf=config.json
2020-01-07 08:45:48 Darwinia IceFrog Node
2020-01-07 08:45:48 Version: 0.4.6-0174b00-x86_64-linux-gnu
2020-01-07 08:45:48   _____                      _       _       
2020-01-07 08:45:48  |  __ \                    (_)     (_)      
2020-01-07 08:45:48  | |  | | __ _ _ ____      ___ _ __  _  __ _ 
2020-01-07 08:45:48  | |  | |/ _` | '__\ \ /\ / / | '_ \| |/ _` |
2020-01-07 08:45:48  | |__| | (_| | |   \ V  V /| | | | | | (_| |
2020-01-07 08:45:48  |_____/ \__,_|_|    \_/\_/ |_|_| |_|_|\__,_|
2020-01-07 08:45:48 Chain specification: Darwinia IceFrog Testnet
2020-01-07 08:45:48 Node name: Flyq
2020-01-07 08:45:48 Roles: "AUTHORITY"
2020-01-07 08:45:58 Highest known block at #134252
2020-01-07 08:45:58 Local node identity is: QmNbU5KY7Y1P5urTMYHCDzEU8NZddy3fYUh3a3MedfEg5e
2020-01-07 08:45:58 Starting BABE Authorship worker
2020-01-07 08:45:59 Discovered new external address for our node: /ip4/101.132.117.50/tcp/23334/p2p/QmNbU5KY7Y1P5urTMYHCDzEU8NZddy3fYUh3a3MedfEg5e
2020-01-07 08:46:05 Idle (2 peers), best: #134252 (0xa8f2…02d7), finalized #115886 (0xdd29…1183), ⬇ 1.8kiB/s ⬆ 0.9kiB/s
2020-01-07 08:46:10 Idle (2 peers), best: #134252 (0xa8f2…02d7), finalized #115886 (0xdd29…1183), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2020-01-07 08:46:15 Idle (2 peers), best: #134252 (0xa8f2…02d7), finalized #115886 (0xdd29…1183), ⬇ 0.5kiB/s ⬆ 0.7kiB/s
2020-01-07 08:46:20 Idle (2 peers), best: #134252 (0xa8f2…02d7), finalized #115886 (0xdd29…1183), ⬇ 2.5kiB/s ⬆ 1.6kiB/s
2020-01-07 08:46:25 Idle (2 peers), best: #134252 (0xa8f2…02d7), finalized #115886 (0xdd29…1183), ⬇ 1.4kiB/s ⬆ 1.1kiB/s
```

**Comment by flyq** [comment]
thx for quickly response

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/issues/2187

**Comment by flyq** [comment]
I clean up the data and restart again, it is syncing.

**Comment by AurevoirXavier** [comment]
> I clean up the data and restart again, it is syncing.

the finalized block?

**Comment by flyq** [comment]
> > I clean up the data and restart again, it is syncing.
> 
> the finalized block?

No.
After panic information, the finalized block jump to 80293 and is blocked again. There is no information about how the finalized block increased to 80293.
```shell
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/da3629b05f8f1b425a738bfe9fe9aedd47c5417a/src/liballoc/boxed.rs:1015
  29: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/da3629b05f8f1b425a738bfe9fe9aedd47c5417a/src/liballoc/boxed.rs:1015
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  30: start_thread
  31: clone


Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /home/sunbobin/.cargo/git/checkouts/substrate-a7fa553ead635512/d2c4b0d/srml/executive/src/lib.rs:277

This is a bug. Please report it at:

        https://github.com/darwinia-network/darwinia/issues/new

2020-01-07 16:39:44 Imported #142306 (0x3e9f…aebd)
2020-01-07 16:39:45 Idle (11 peers), best: #142307 (0xf657…3dc1), finalized #80293 (0x0936…e028), ⬇ 6.0kiB/s ⬆ 411.5kiB/s
2020-01-07 16:39:48 Imported #142308 (0x3a8e…1506)
2020-01-07 16:39:48 Imported #142308 (0x656d…ab68)
2020-01-07 16:39:50 Idle (11 peers), best: #142308 (0x3a8e…1506), finalized #80293 (0x0936…e028), ⬇ 8.0kiB/s ⬆ 296.9kiB/s
2020-01-07 16:39:52 Reorg from #142308,0x3a8e…1506 to #142309,0x7766…f99b, common ancestor #142307,0xf657…3dc1
2020-01-07 16:39:52 Imported #142309 (0x7766…f99b)
2020-01-07 16:39:54 Imported #142310 (0x1ae4…7401)
2020-01-07 16:39:55 Idle (11 peers), best: #142310 (0x1ae4…7401), finalized #80293 (0x0936…e028), ⬇ 8.9kiB/s ⬆ 423.4kiB/s
```

**Comment by flyq** [comment]
Maybe there are some bugs in implement of grandpa consensus algorithm

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/issues/2304

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/issues/2304#issuecomment-484557571

> ```
> logs-from-cennznet-validators-validator-0-in-cennznet-validators-validator-0-0.txt:2019-04-18 01:17:25.549 main DEBUG afg  Voter VALIDATOR_0 noting beginning of round (Round(551), SetId(0)) to network.
> logs-from-cennznet-validators-validator-1-in-cennznet-validators-validator-1-0:2019-04-18 01:17:32.213 main DEBUG afg  Voter VALIDATOR_1 noting beginning of round (Round(550), SetId(0)) to network.
> logs-from-cennznet-validators-validator-2-in-cennznet-validators-validator-2-0.txt:2019-04-18 01:17:16.724 main DEBUG afg  Voter VALIDATOR_2 noting beginning of round (Round(550), SetId(0)) to network.
> logs-from-cennznet-validators-validator-3-in-cennznet-validators-validator-3-0:2019-04-18 01:17:25.558 main DEBUG afg  Voter VALIDATOR_3 noting beginning of round (Round(550), SetId(0)) to network.
> ```
> 
> So it seems that one of the validators progressed to the next round (maybe because the other authorities didn't see its vote), while the other authorities are stuck in round 550 and probably don't have threshold stake to finalize. What you should do to get finality started again is disable all validators and copy the database from validator 0 into the other validators' nodes, this way when you restart the nodes they'll all be at round 551.
> 
> We are working on improvements to fix these situations where it can get stuck with a small amount of validators ([9631622](https://github.com/paritytech/substrate/commit/9631622fca89709914cec8a3680e5034c51b2519) was recently merged which should help as well).

```
0|icefrog  | 2020-01-10 17:01:30.118 main-tokio-2 INFO substrate  Imported #215066 (0xae51…e342)
0|icefrog  | 2020-01-10 17:01:32.773 main-tokio-14 TRACE afg  Polling round 1, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
0|icefrog  | 2020-01-10 17:01:32.832 main-tokio-2 INFO substrate  Idle (5 peers), best: #215066 (0xae51…e342), finalized #76059 (0x10b0…b9ff), ⬇ 8.1kiB/s ⬆ 4.6kiB/s
0|icefrog  | 2020-01-10 17:01:33.101 main-tokio-0 TRACE afg  Polling round 1, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
0|icefrog  | 2020-01-10 17:01:33.101 main-tokio-12 INFO substrate  Imported #215067 (0x02ce…1433)
0|icefrog  | 2020-01-10 17:01:34.043 main-tokio-0 INFO darwinia_cli::informant  Reorg from #215067,0x02ce…1433 to #215067,0xedec…ff3a, common ancestor #215066,0xae51…e342
0|icefrog  | 2020-01-10 17:01:34.043 main-tokio-12 TRACE afg  Polling round 1, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
0|icefrog  | 2020-01-10 17:01:34.043 main-tokio-0 INFO substrate  Imported #215067 (0xedec…ff3a)
0|icefrog  | 2020-01-10 17:01:36.170 main-tokio-2 INFO substrate  Imported #215068 (0xc565…bba4)
0|icefrog  | 2020-01-10 17:01:36.170 main-tokio-14 TRACE afg  Polling round 1, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
0|icefrog  | 2020-01-10 17:01:37.772 main-tokio-6 TRACE afg  Polling round 1, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
0|icefrog  | 2020-01-10 17:01:37.772 main-tokio-2 TRACE afg  Polling round 1, state = State { prevote_ghost: None, finalized: None, estimate: None, completable: false }, step = Some(Prevoted)
```

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/issues/4586

**Comment by karanchopraa** [comment]
how to solve this problem, anyone knows what to do?

**Comment by AurevoirXavier** [comment]
> how to solve this problem, anyone knows what to do?

Update Substrate version.
