### ISSUE TITLE
Storage Root Must Match that Calculated

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#369]
We find a really strange scenario that will break the exsist blockchain network.

Here is the scenario.
Alice and Bob are happy to build a blockchain network, and producing about 20000 blocks.
- Node1: Alice, Binary 1
- Node2: Bob, Binary 1

Node3 wants to join the network, but she uses Alice's key and the same version number but different binary.
- Node3: Alice, Binary 2 (But the version naming is the same, the binary is compiled by the code with a little changing)

Now, Node1 and Node2 stop producing the blocks, and Node3 can not join the network and produce a little block for herself.

Following is the log from Node1,  but we are missing the log on Node3.
```rust
2020-03-20 06:01 +00:00: Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', <::std::macros::panic macros>:2
2020-03-20 06:01 +00:00:
2020-03-20 06:01 +00:00: This is a bug. Please report it at:
2020-03-20 06:01 +00:00:
2020-03-20 06:01 +00:00: 	https://github.com/darwinia-network/darwinia/issues/new
2020-03-20 06:01 +00:00:
2020-03-20 06:01 +00:00: 2020-03-20 06:01:33 Block prepare storage changes error:
2020-03-20 06:01 +00:00: Execution(RuntimePanicked("Storage root must match that calculated."))
2020-03-20 06:01 +00:00:
2020-03-20 06:01 +00:00: ====================
2020-03-20 06:01 +00:00:
2020-03-20 06:01 +00:00: Version: 0.5.0-ccfbeb2-x86_64-linux-gnu
2020-03-20 06:01 +00:00:
2020-03-20 06:01 +00:00:   0: sp_panic_handler::set::{{closure}}
2020-03-20 06:01 +00:00: 1: std::panicking::rust_panic_with_hook
2020-03-20 06:01 +00:00:              at src/libstd/panicking.rs:474
2020-03-20 06:01 +00:00:    2: std::panicking::begin_panic
2020-03-20 06:01 +00:00: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
2020-03-20 06:01 +00:00: sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::
2020-03-20 06:01 +00:00: traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module
2020-03-20 06:01 +00:00: <node_runtime::Runtime> as sp_runtime::traits::StaticLookup>::Source,node_runtime::Call,sp_runtime::MultiSignature,(frame_system::CheckVersion<node_runtime::Runtime>, frame_system::CheckGenesis<node_runtime::Runtime>, frame_system::CheckEra<node_runtime::Runtime>, frame_system::CheckNonce<node_runtime::Runtime>,
2020-03-20 06:01 +00:00:  frame_system::CheckWeight<node_runtime::Runtime>, pallet_transaction_payment::ChargeTransactionPayment<node_runtime::Runtime>, pallet_contracts::CheckBlockGasLimit<node_runtime::Runtime>)>>>>::execute_block
2020-03-20 06:01 +00:00:    5: std::panicking::try::do_call
2020-03-20 06:01 +00:00:   6: __rust_maybe_catch_panic
2020-03-20 06:01 +00:00:              at src/libpanic_unwind/lib.rs:86
2020-03-20 06:01 +00:00:    7: std::thread::local::LocalKey<T>::with
2020-03-20 06:01 +00:00:    8: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
2020-03-20 06:01 +00:00: ::RuntimeCache::with_instance
2020-03-20 06:01 +00:00:   10: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
2020-03-20 06:01 +00:00:   11: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
2020-03-20 06:01 +00:00:   12: sp_state_machine::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
2020-03-20 06:01 +00:00:  as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
2020-03-20 06:01 +00:00:   14: <sc_client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
2020-03-20 06:01 +00:00:   15: sp_api::runtime_decl_for_Core::execute_block_call_api_at
2020-03-20 06:01 +00:00:   16: sp_api::Core::execute_block
2020-03-20 06:01 +00:00: Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
2020-03-20 06:01 +00:00:   18: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
2020-03-20 06:01 +00:00:   19: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
2020-03-20 06:01 +00:00:  20: sp_consensus::import_queue::import_single_block
2020-03-20 06:01 +00:00:   21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
2020-03-20 06:01 +00:00:   22: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
2020-03-20 06:01 +00:00: 23: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
2020-03-20 06:01 +00:00:   24: futures_executor::thread_pool::PoolState::work
2020-03-20 06:01 +00:00:   25: std::sys_common::backtrace::__rust_begin_short_backtrace
2020-03-20 06:01 +00:00:   26: std::panicking::try::do_call
2020-03-20 06:01 +00:00:   27: __rust_maybe_catch_panic
2020-03-20 06:01 +00:00:              at src/libpanic_unwind/lib.rs:86
2020-03-20 06:01 +00:00:   28: core::ops::function::FnOnce::call_once{{vtable.shim}}
2020-03-20 06:01 +00:00: F> as core::ops::function::FnOnce<A>>::call_once
2020-03-20 06:01 +00:00:              at /rustc/75cf41afb468152611212271bae026948cd3ba46/src/liballoc/boxed.rs:1017
2020-03-20 06:01 +00:00: ::call_once
2020-03-20 06:01 +00:00:              at /rustc/75cf41afb468152611212271bae026948cd3ba46/src/liballoc/boxed.rs:1017
2020-03-20 06:01 +00:00:       std::sys_common::thread::start_thread
2020-03-20 06:01 +00:00:              at src/libstd/sys_common/thread.rs:13
2020-03-20 06:01 +00:00:       std::sys::unix::thread::Thread::new::thread_start
2020-03-20 06:01 +00:00:              at src/libstd/sys/unix/thread.rs:80
2020-03-20 06:01 +00:00:   31: start_thread
```

**Comment by yanganto** [comment]
Maybe this is caused by different version of runtime?

**Comment by AurevoirXavier** [comment]
There're two node in the tests env. (Alice and Bob are same version)

But someone boot up new Alice Bob node with different version. The new Alice/Bob seems not connect to the old one (peer 1 not 2).

**Comment by yanganto** [comment]
I refined the detail of the issue if there is something missing, please correct.

**Comment by AurevoirXavier** [comment]
Seems to be an accident. Move to #396.
