### ISSUE TITLE
Storage Root Must Match that Calculated

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#396]
Version: https://github.com/darwinia-network/darwinia/tree/cf4c7be1cf6671144cc4f4ecd7140e9023a5dbaf

```rust
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: ====================
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: Version: 0.5.0-ffb88b8-x86_64-linux-gnu
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:    0: sp_panic_handler::set::{{closure}}
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:    1: std::panicking::rust_panic_with_hook
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:              at src/libstd/panicking.rs:474
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:    2: std::panicking::begin_panic
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:    3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:    4: <node_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module<node_runtime::Runtime> as sp_runtime::traits::StaticLookup>::Source,node_runtime::Call,sp_runtime::MultiSignature,(frame_system::CheckVersion<node_runtime::Runtime>, frame_system::CheckGenesis<node_runtime::Runtime>, frame_system::CheckEra<node_runtime::Runtime>, frame_system::CheckNonce<node_runtime::Runtime>, frame_system::CheckWeight<node_runtime::Runtime>, pallet_transaction_payment::ChargeTransactionPayment<node_runtime::Runtime>, pallet_contracts::CheckBlockGasLimit<node_runtime::Runtime>)>>>>::execute_block
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:    5: std::panicking::try::do_call
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:    6: __rust_maybe_catch_panic
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:              at src/libpanic_unwind/lib.rs:86
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:    7: std::thread::local::LocalKey<T>::with
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: native_executor
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: ::
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: WasmExecutor::with_instance::{{closure}}
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:    9: sc_executor::wasm_runtime::RuntimeCache::with_instance
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   10: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   11: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   12: sp_state_machine::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   13: <sc_client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   14: <sc_client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   15: sp_api::runtime_decl_for_Core::execute_block_call_api_at
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   16: sp_api::Core::execute_block
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   17: <&sc_client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   18: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   19: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   20: sp_consensus::import_queue::import_single_block
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:  21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   22: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   23: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   24: futures_executor::thread_pool::PoolState::work
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   25: std::sys_common::backtrace::__rust_begin_short_backtrace
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   26: std::panicking::try::do_call
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   27: __rust_maybe_catch_panic
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:              at src/libpanic_unwind/lib.rs:86
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   28: core::ops::function::FnOnce::call_once{{vtable.shim}}
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   29: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:              at /rustc/75cf41afb468152611212271bae026948cd3ba46/src/liballoc/boxed.rs:1017
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   30: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:              at /rustc/75cf41afb468152611212271bae026948cd3ba46/src/liballoc/boxed.rs:1017
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:       std::sys_common::thread::start_thread
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:              at src/libstd/sys_common/thread.rs:13
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:       std::sys::unix::thread::Thread::new::thread_start
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:              at src/libstd/sys/unix/thread.rs:80
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   31: start_thread
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:   32: __clone
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', <::std::macros::panic macros>:2
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: This is a bug. Please report it at:
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: 	https://github.com/darwinia-network/darwinia/issues/new
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00:
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: 2020-03-25 10:04:29 Block prepare storage changes error:
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: Execution(RuntimePanicked("Storage root must match that calculated."))
30|darwinia-canary-1  | 2020-03-25 10:04 +00:00: Hash: given=be9305c7c0e359f0e3078649ccb82c476677821ea0635f51723e88f1734d7b72, expected=093024de0b76748250007b43c7fb82f6f508eb645377741eefaf4002ec8ba5fa

```

**Comment by AurevoirXavier** [comment]
Pay more attention to `Native` and `WASM`.
