### ISSUE TITLE
节点异常退出

### ISSUE THREAD

**Issue by hging** [darwinia-network/darwinia#41]
日志如下：
```
2019-07-08 09:32:06 Pre-sealed block for proposal at 62199. Hash now 0xe882f14e6eeff9541ab1074e8c7392a062412191c4437c06e1cc8df1e72818d4, previously 0x6f04aac860a893b04b27842547bf299bb458b8ea1e107ab1c0d1f2fd434de084.
Hash: given=6a01ad3815635208af782d55aed3b98aaf709ede06e6bda282e783e874406ba1, expected=6457ff9f6571232b58b0bbf49298f5c8c0d5d24bc8c59ec7e0fdbf033af25a8d

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::hb9086efd4a6065e1 (0x559c24bd6b60)
   1: rust_panic_with_hook (0x559c24d620f9)
             at src/libstd/panicking.rs:478
   2: std::panicking::begin_panic::h95d5f94f8a7547ad (0x559c242b5415)
   3: srml_executive::Executive<System,Block,Context,Payment,UnsignedValidator,AllModules>::execute_block::h2539172a66a28c47 (0x559c24320238)
   4: node_runtime::api::dispatch::hfef69179bfe9b40c (0x559c242c0451)
   5: std::panicking::try::do_call::h7ba3fb6d4799e972 (0x559c242a8b32)
   6: __rust_maybe_catch_panic (0x559c24d6743a)
             at src/libpanic_unwind/lib.rs:87
   7: substrate_executor::native_executor::safe_call::h4cc995b43e7e8876 (0x559c242a89da)
   8: std::thread::local::LocalKey<T>::with::h78a289a35a741370 (0x559c242a8467)
   9: <node_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::hc41cdb4d8ab7dc14 (0x559c242a7fed)
  10: std::thread::local::LocalKey<T>::with::ha0389a6041e88581 (0x559c23dbc4ba)
  11: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h5c08d41a09de06f3 (0x559c240773b3)
  12: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_call_with_native_else_wasm_strategy::h611a9deb7979b0b7 (0x559c240c2a13)
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h0d5ed3fa1bd4e154 (0x559c24080efb)
  14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h42587a21d90c89d0 (0x559c23e05d52)
  15: <substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h0dd299dd4b967531 (0x559c23d03a69)
  16: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,PRA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hbb1283e4b7a3dbcb (0x559c2406bde6)
  17: <futures::future::map::Map<A,F> as futures::future::Future>::poll::h627c342cdf6feab1 (0x559c23e81e55)
  18: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h0dfa51beacfed793 (0x559c2416afee)
  19: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h6b9ed871176cecee (0x559c2416d6be)
  20: <&mut F as futures::future::Future>::poll::h344dc31e2855c4e0 (0x559c23f01b7d)
  21: std::panicking::try::do_call::h7ea1581a740f8ce2 (0x559c23e275fa)
  22: __rust_maybe_catch_panic (0x559c24d6743a)
             at src/libpanic_unwind/lib.rs:87
  23: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll::h7d3980ebe0123d47 (0x559c23debdd7)
  24: <futures::future::select::Select<A,B> as futures::future::Future>::poll::h3abfed3022c1282d (0x559c23e873f7)
  25: futures::future::chain::Chain<A,B,C>::poll::h1b0545a2a8838144 (0x559c240e3249)
  26: futures::task_impl::std::set::h0dbee74b9c229bfa (0x559c24a76df2)
  27: futures::task_impl::Spawn<T>::poll_future_notify::h472f28e6c521a66a (0x559c24a77be6)
  28: std::panicking::try::do_call::h9334a1163aea8408 (0x559c24a7b0b1)
  29: __rust_maybe_catch_panic (0x559c24d6743a)
             at src/libpanic_unwind/lib.rs:87
  30: tokio_threadpool::task::Task::run::hd8bb022254236495 (0x559c24a7b59c)
  31: tokio_threadpool::worker::Worker::run_task::h765f41a0a50bbba8 (0x559c24a73565)
  32: tokio_threadpool::worker::Worker::run::h424b95e4eec0d070 (0x559c24a72a5e)
  33: tokio_trace_core::dispatcher::with_default::h566a73fea286aece (0x559c24a5fb17)
  34: std::thread::local::LocalKey<T>::with::h38c8151ed26097a9 (0x559c24a5c876)
  35: std::thread::local::LocalKey<T>::with::h6c40aae6796ab9ad (0x559c24a5ca3e)
  36: std::thread::local::LocalKey<T>::with::h00ff5a188919a297 (0x559c24a5c6b4)
  37: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h6422ab2946b85b1b (0x559c24a60477)
  38: std::thread::local::LocalKey<T>::with::hba1f8666e05ddba1 (0x559c24a7be93)
  39: std::thread::local::LocalKey<T>::with::hd3fecc8ba3b5e401 (0x559c24a7bfce)
  40: std::sys_common::backtrace::__rust_begin_short_backtrace::h4be1364c9cc25195 (0x559c24a7adc1)
  41: std::panicking::try::do_call::hfed7f7de37a6ad19 (0x559c24a7b0fc)
  42: __rust_maybe_catch_panic (0x559c24d6743a)
             at src/libpanic_unwind/lib.rs:87
  43: core::ops::function::FnOnce::call_once{{vtable.shim}}::hd440b11de224c567 (0x559c24a74da0)
  44: call_once<(),FnBox<()>> (0x559c24d4f7cf)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
  45: call_once<(),alloc::boxed::Box<FnBox<()>>> (0x559c24d667a0)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:80
  46: start_thread (0x7f56e28456db)
  47: __clone (0x7f56e235688f)
  48: <unknown> (0x0)

Thread 'main-tokio-4' panicked at 'Storage root must match that calculated.', /home/hammerWang/.cargo/git/checkouts/substrate-7e08433d4c370a21/277e2f9/srml/executive/src/lib.rs:325

This is a bug. Please report it at:

	https://github.com/darwinia-network/darwinia/issues/new

2019-07-08 09:32:06 Imported #62199 (0xe882…18d4)
/rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/ops/arith.rs
443
45

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::hb9086efd4a6065e1 (0x559c24bd6b60)
   1: rust_panic_with_hook (0x559c24d620f9)
             at src/libstd/panicking.rs:478
   2: continue_panic_fmt (0x559c24d61b92)
             at src/libstd/panicking.rs:381
   3: rust_begin_unwind (0x559c24d61a76)
   4: panic_fmt (0x559c24d7b8cd)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h319d9c1c2f69455d (0x559c2415dcee)
   6: <C as substrate_service::components::OffchainWorker<C>>::offchain_workers::h135fa292665b489a (0x559c2416304c)
   7: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::hdadb65f4ac19b3e8 (0x559c23f2addb)
   8: <futures::future::select::Select<A,B> as futures::future::Future>::poll::hd0691669209cf712 (0x559c23e8d27c)
   9: futures::future::chain::Chain<A,B,C>::poll::haaa25159ea68be97 (0x559c240e6a59)
  10: futures::task_impl::std::set::h0dbee74b9c229bfa (0x559c24a76df2)
  11: futures::task_impl::Spawn<T>::poll_future_notify::h472f28e6c521a66a (0x559c24a77be6)
  12: std::panicking::try::do_call::h9334a1163aea8408 (0x559c24a7b0b1)
  13: __rust_maybe_catch_panic (0x559c24d6743a)
             at src/libpanic_unwind/lib.rs:87
  14: tokio_threadpool::task::Task::run::hd8bb022254236495 (0x559c24a7b59c)
  15: tokio_threadpool::worker::Worker::run_task::h765f41a0a50bbba8 (0x559c24a73565)
  16: tokio_threadpool::worker::Worker::run::h424b95e4eec0d070 (0x559c24a72c69)
  17: tokio_trace_core::dispatcher::with_default::h566a73fea286aece (0x559c24a5fb17)
  18: std::thread::local::LocalKey<T>::with::h38c8151ed26097a9 (0x559c24a5c876)
  19: std::thread::local::LocalKey<T>::with::h6c40aae6796ab9ad (0x559c24a5ca3e)
  20: std::thread::local::LocalKey<T>::with::h00ff5a188919a297 (0x559c24a5c6b4)
  21: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h6422ab2946b85b1b (0x559c24a60477)
  22: std::thread::local::LocalKey<T>::with::hba1f8666e05ddba1 (0x559c24a7be93)
  23: std::thread::local::LocalKey<T>::with::hd3fecc8ba3b5e401 (0x559c24a7bfce)
  24: std::sys_common::backtrace::__rust_begin_short_backtrace::h4be1364c9cc25195 (0x559c24a7adc1)
  25: std::panicking::try::do_call::hfed7f7de37a6ad19 (0x559c24a7b0fc)
  26: __rust_maybe_catch_panic (0x559c24d6743a)
             at src/libpanic_unwind/lib.rs:87
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}::hd440b11de224c567 (0x559c24a74da0)
  28: call_once<(),FnBox<()>> (0x559c24d4f7cf)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
  29: call_once<(),alloc::boxed::Box<FnBox<()>>> (0x559c24d667a0)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:80
  30: start_thread (0x7f56e28456db)
  31: __clone (0x7f56e235688f)
  32: <unknown> (0x0)

Thread 'main-tokio-6' panicked at 'called `Result::unwrap()` on an `Err` value: Execution(Wasmi(Trap(Trap { kind: Unreachable })))', src/libcore/result.rs:997

This is a bug. Please report it at:

	https://github.com/darwinia-network/darwinia/issues/new
```

**Comment by AurevoirXavier** [comment]
Issue report bugs with a old versions of darwinia.
