### ISSUE TITLE
Storage root must match that calculated

### ISSUE THREAD

**Issue by freehere107** [darwinia-network/darwinia#479]
Version 0.6.3

0|darwinia-canary  | 2020-07-27 00:44 +00:00: 2020-07-27 00:44:59 💸 new validator set of size 31 has been elected via ElectionCompute::Unsigned for era 335
0|darwinia-canary  | 2020-07-27 00:44 +00:00: Hash: given=0dabb31fd40c16852f8becf45a62949f252d9703bc2b2d4c8520b001058c282f, expected=62a45af8b51042dfb5fcb2f8f5bbf9ad325734543dc4c5efce34965ca6830ec0
0|darwinia-canary  | 2020-07-27 00:44 +00:00:
0|darwinia-canary  | 2020-07-27 00:44 +00:00: ====================
0|darwinia-canary  | 2020-07-27 00:44 +00:00:
0|darwinia-canary  | 2020-07-27 00:44 +00:00: Version: 0.6.3-fde4b48-x86_64-linux-gnu
0|darwinia-canary  | 2020-07-27 00:44 +00:00:
0|darwinia-canary  | 2020-07-27 00:44 +00:00:    0: sp_panic_handler::set::{{closure}}
0|darwinia-canary  | 2020-07-27 00:44 +00:00:    1: std::panicking::rust_panic_with_hook
0|darwinia-canary  | 2020-07-27 00:44 +00:00:              at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:530
0|darwinia-canary  | 2020-07-27 00:44 +00:00:    2: std::panicking::begin_panic
0|darwinia-canary  | 2020-07-27 00:44 +00:00:    3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
0|darwinia-canary  | 2020-07-27 00:44 +00:00: Runtime>,frame_system::CheckGenesis<crab_runtime::Runtime>,frame_system::CheckEra<crab_runtime::Runtime>,frame_system::CheckNonce<crab_runtime::Runtime>,frame_system::CheckWeight<crab_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<crab_runtime::Runtime>,pallet_grandpa::equivocation::ValidateEquivocationReport<crab_runtime::Runtime>,darwinia_eth_relay::CheckEthRelayHeaderHash<crab_runtime::Runtime>)>>>>::execute_block
0|darwinia-canary  | 2020-07-27 00:44 +00:00:    5: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
0|darwinia-canary  | 2020-07-27 00:44 +00:00:    6: std::thread::local::LocalKey<T>::with
0|darwinia-canary  | 2020-07-27 00:44 +00:00:    7: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
0|darwinia-canary  | 2020-07-27 00:44 +00:00:    8: sc_executor::wasm_runtime::RuntimeCache::with_instance
0|darwinia-canary  | 2020-07-27 00:44 +00:00:    9: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   10: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   11: sp_state_machine::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   12: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   13: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
0|darwinia-canary  | 2020-07-27 00:44 +00:00: runtime_decl_for_Core::execute_block_call_api_at
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   15: sp_api::Core::execute_block
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   16: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   17: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   18: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   19: sp_consensus::import_queue::import_single_block
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   21: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   22: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   23: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   24: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   25: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   27: std::thread::local::LocalKey<T>::with
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   28: futures_executor::local_pool::block_on
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   29: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   30: tokio::runtime::task::core::Core<T,S>::poll
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   32: tokio::runtime::task::harness::Harness<T,S>::poll
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   33: tokio::runtime::blocking::pool::Inner::run
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   34: tokio::runtime::context::enter
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   35: std::sys_common::backtrace::__rust_begin_short_backtrace
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   36: core::ops::function::FnOnce::call_once{{vtable.shim}}
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   37: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
0|darwinia-canary  | 2020-07-27 00:44 +00:00:              at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081
0|darwinia-canary  | 2020-07-27 00:44 +00:00:       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
0|darwinia-canary  | 2020-07-27 00:44 +00:00: /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081
0|darwinia-canary  | 2020-07-27 00:44 +00:00:       std::sys::unix::thread::Thread::new::thread_start
0|darwinia-canary  | 2020-07-27 00:44 +00:00:              at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/sys/unix/thread.rs:87
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   38: start_thread
0|darwinia-canary  | 2020-07-27 00:44 +00:00:   39: __clone
0|darwinia-canary  | 2020-07-27 00:44 +00:00:
0|darwinia-canary  | 2020-07-27 00:44 +00:00:
0|darwinia-canary  | 2020-07-27 00:44 +00:00: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/macros.rs:13
0|darwinia-canary  | 2020-07-27 00:44 +00:00:
0|darwinia-canary  | 2020-07-27 00:44 +00:00: This is a bug. Please report it at:
0|darwinia-canary  | 2020-07-27 00:44 +00:00:
0|darwinia-canary  | 2020-07-27 00:44 +00:00: 	https://github.com/darwinia-network/darwinia/issues/new
0|darwinia-canary  | 2020-07-27 00:44 +00:00:
0|darwinia-canary  | 2020-07-27 00:44 +00:00: 2020-07-27 00:44:59 Block prepare storage changes error:
0|darwinia-canary  | 2020-07-27 00:44 +00:00: Execution(RuntimePanicked("Storage root must match that calculated."))

**Comment by HackFisher** [comment]
https://github.com/paritytech/substrate/issues/5112

**Comment by AurevoirXavier** [comment]
After revert to the latest finalize block

```rust
2020-07-27 10:24:02 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWDXjxHayRC2Vmc3Cs7p4YMdQCpTs9dbAagvKv9vnhqpp9, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:02 💔 Error importing block 0x2ec0c8aeaeb56f378a8c9e3019392157846bd25d01a20532ca875f975243b590: Err(UnknownParent)
2020-07-27 10:24:02 💔 Error importing block 0x8a4bc853b192b50bf56c1c1ef4cfec1c98fe7fb261c4d0defcd0bec77673951f: Err(UnknownParent)
2020-07-27 10:24:03 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWF8wF5KJkajvp8jtr1w7nBcrX7kiB92V7wrAVJfXYfoS5, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:05 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWMKqW63DvQEACXNtGfxCQsukJQMBoJqWYkPYspCXJPqCn, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:05 ⚙️  Syncing, target=#1115990 (7 peers), best: #1115695 (0x74ab…1de5), finalized #1115693 (0xa2b9…dda6), ⬇ 67.5kiB/s ⬆ 58.7kiB/s
2020-07-27 10:24:07 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWLtv1WboMKnUg1J5KorJM9nee92LgJXB3m3AHRhXfCrbQ, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:08 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooW9sjm3usL1YiooAZKJXyDmPcGKXEHKWmTALvBgNipNGB1, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:08 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWDXjxHayRC2Vmc3Cs7p4YMdQCpTs9dbAagvKv9vnhqpp9, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:09 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWF8wF5KJkajvp8jtr1w7nBcrX7kiB92V7wrAVJfXYfoS5, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:10 ⚙️  Syncing  0.0 bps, target=#1115703 (12 peers), best: #1115695 (0x74ab…1de5), finalized #1115693 (0xa2b9…dda6), ⬇ 86.5kiB/s ⬆ 123.8kiB/s
2020-07-27 10:24:15 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWMKqW63DvQEACXNtGfxCQsukJQMBoJqWYkPYspCXJPqCn, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:15 🔍 Discovered new external address for our node: /ip4/10.156.3.194/tcp/30333/p2p/12D3KooWFHNgAmrphmgcgukREKRrwWn6pZ6qQ8eFVXsRdnUQKZvL
2020-07-27 10:24:15 ⚙️  Syncing  0.0 bps, target=#1115992 (16 peers), best: #1115695 (0x74ab…1de5), finalized #1115693 (0xa2b9…dda6), ⬇ 35.2kiB/s ⬆ 95.2kiB/s
2020-07-27 10:24:16 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooW9sjm3usL1YiooAZKJXyDmPcGKXEHKWmTALvBgNipNGB1, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:16 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWMKqW63DvQEACXNtGfxCQsukJQMBoJqWYkPYspCXJPqCn, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:19 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWRPDfwtHMmWP8gunx6UUSK2i2w9eUb5FPHwwsR5123u8R, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:19 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWF8wF5KJkajvp8jtr1w7nBcrX7kiB92V7wrAVJfXYfoS5, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:20 ⚙️  Syncing  0.0 bps, target=#1115992 (19 peers), best: #1115695 (0x74ab…1de5), finalized #1115693 (0xa2b9…dda6), ⬇ 69.8kiB/s ⬆ 104.3kiB/s
2020-07-27 10:24:25 ⚙️  Syncing  0.0 bps, target=#1115994 (22 peers), best: #1115695 (0x74ab…1de5), finalized #1115693 (0xa2b9…dda6), ⬇ 33.6kiB/s ⬆ 87.5kiB/s
2020-07-27 10:24:26 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWLtv1WboMKnUg1J5KorJM9nee92LgJXB3m3AHRhXfCrbQ, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:26 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooW9sjm3usL1YiooAZKJXyDmPcGKXEHKWmTALvBgNipNGB1, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:27 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWAke1oeub6EqData2Y2J7reDmcCnXuuAV3J117UC1HPAg, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:31 ⚙️  Syncing  0.0 bps, target=#1115724 (19 peers), best: #1115695 (0x74ab…1de5), finalized #1115693 (0xa2b9…dda6), ⬇ 42.6kiB/s ⬆ 92.1kiB/s
2020-07-27 10:24:32 💔 Verification failed for block 0xa8683120aac97c80f1c5259bfa7c767290d9612de5d861686d362bd415e95ee2 received from peer: 12D3KooWHwqDTQXM76cKr5HWNaSMLNWoh2zvPr1hrzJUJW8V6hm4, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
2020-07-27 10:24:33 💔 Verification failed for block 0x9d9f520a92c1ebbb452d4fb69e28f08886f5a48cbb3169b8996f98a27ccbf0db received from peer: 12D3KooWRPDfwtHMmWP8gunx6UUSK2i2w9eUb5FPHwwsR5123u8R, "Client error: UnknownBlock: header not found in db: 0x9d9f…f0db"
```

**Comment by AurevoirXavier** [comment]
> https://github.com/polkascan/polkascan-os/issues/6
>
> The block cannot be found on your node.
> Either you are looking up a block by hash on the wrong network, or more likely you are not running an archive node and the block has already been pruned from the state.

**Comment by AurevoirXavier** [comment]
with `--execution-syncing wasm`, `--execution-import-block wasm`

```rust
2020-07-27 10:33:24 Unable to fetch epoch data at block 0x74ab93e68a53e4c4aa9f5624748fd616604e8cc286341d57b22bb08ec05c1de5: ChainLookup("Client(UnknownBlock(\"header not found in db: 0x9d9f…f0db\"))")
```

**Comment by AurevoirXavier** [comment]
move to #481
