### ISSUE TITLE
Panic while starting darwinia-0.6.6-x86_64-linux-gnu-glibc-2.17-llvm-3.8.tar.bz2 without parameters

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/darwinia#493]
## OS

```
Linux VM-16-16-ubuntu 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## Logs

```
ubuntu@VM-16-16-ubuntu:~$ ./darwinia-0.6.6-x86_64-linux-gnu-glibc-2.17-llvm-3.8 

====================

Version: 0.6.6-55f151b-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panicking.rs:530
   2: std::panicking::begin_panic
   3: darwinia_cli::command::<impl sc_cli::SubstrateCli for darwinia_cli::cli::Cli>::load_spec
   4: sc_cli::config::CliConfiguration::create_configuration
   5: sc_cli::runner::Runner<C>::new
   6: darwinia_cli::Configuration::create_runner
   7: darwinia_cli::command::run
   8: darwinia::main
   9: std::rt::lang_start::{{closure}}
  10: std::rt::lang_start_internal::{{closure}}
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panicking.rs:348
      std::panicking::try
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panicking.rs:325
      std::panic::catch_unwind
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/rt.rs:51
  11: main
  12: __libc_start_main
  13: <unknown>


Thread 'main' panicked at 'not implemented', cli/src/command.rs:83

This is a bug. Please report it at:

	https://github.com/darwinia-network/darwinia/issues/new
```

**Comment by AurevoirXavier** [comment]
Please read the  README.

`--chain crab`

**Comment by clearloop** [comment]
> Please read the RELEASE NOTE/README.
> 
> `--chain crab`

 I know `--chain crab` can start the node, this panic should be fixed.

**Comment by AurevoirXavier** [comment]
> > Please read the RELEASE NOTE/README.
> > `--chain crab`
> 
> I know `--chain crab` can start the node, this panic should be fixed.

Default is mainnet. Release in next version.
