### ISSUE TITLE
Thread 'main' panicked at 'not implemented', cli/src/command.rs:83

### ISSUE THREAD

**Issue by banatarski** [darwinia-network/darwinia#499]
I was setting up a Darwinia node, after finishing compiling i get the following error.

```
======================
Finished release [optimized] target(s) in 32m 40s
     Running `target/release/darwinia --base-path /tmp/username --validator --port 20222 --ws-port 9964 --rpc-port 9963 --name nodename --rpc-cors=all --bootnodes /ip4/95.217.192.222/tcp/20222/p2p/12D3KooWE3ZPjnoMPvqwRimAsNrmZP6XL1Y8Dw2Cca2xBJYsBWjA /ip4/49.234.225.216/tcp/30333/p2p/12D3KooWFHNgAmrphmgcgukREKRrwWn6pZ6qQ8eFVXsRdnUQKZvL /ip4/106.54.116.32/tcp/30333/p2p/12D3KooWKhcHAUCs2CUGA5NtRnRRarL4C5U7fVB4ycmHxDidZsrj /ip4/35.234.33.88/tcp/30333/p2p/12D3KooWMCTzZVwJCafwPVQGxr8CkSK1VKmg5pbhjKjqgEwhywSe`
====================

Version: 0.6.6-55f151b-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d/library/std/src/panicking.rs:573
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: darwinia_cli::command::<impl sc_cli::SubstrateCli for darwinia_cli::cli::Cli>::load_spec
   6: sc_cli::config::CliConfiguration::create_configuration
   7: sc_cli::runner::Runner<C>::new
   8: darwinia_cli::Configuration::create_runner
   9: darwinia_cli::command::run
  10: darwinia::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::rt::lang_start::{{closure}}
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d/library/core/src/ops/function.rs:265
      std::panicking::try::do_call
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d/library/std/src/panicking.rs:373
      std::panicking::try
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d/library/std/src/panicking.rs:337
      std::panic::catch_unwind
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d/library/std/src/panic.rs:379
      std::rt::lang_start_internal
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d/library/std/src/rt.rs:51
  14: main
  15: __libc_start_main
  16: _start


Thread 'main' panicked at 'not implemented', cli/src/command.rs:83

This is a bug. Please report it at:

	https://github.com/darwinia-network/darwinia/issues/new
```

**Comment by AurevoirXavier** [comment]
Dup #493

**Comment by HackFisher** [comment]
@banatarski use ```--chain crab``` to start crab nodes

Refer: https://github.com/darwinia-network/darwinia/releases/tag/v0.6.6

**Comment by banatarski** [comment]
> @banatarski use `--chain crab` to start crab nodes
> 
> Refer: https://github.com/darwinia-network/darwinia/releases/tag/v0.6.6

Thanks @HackFisher, followed the dup that @AurevoirXavier linked and found the solution.
