### ISSUE TITLE
Crab node panic logs captured recently.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia#879]
```
2022-05-07 05:45:42 ✨ Imported #10357118 (0x7659…eeb2)

====================

Version: 0.12.1-unknown-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:502:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panicking.rs:106:14
   6: core::panicking::panic_display
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panicking.rs:62:5
   7: core::option::expect_failed
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/option.rs:1637:5
   8: sc_state_db::noncanonical::discard_descendants
   9: sc_state_db::noncanonical::discard_descendants
  10: sc_state_db::noncanonical::discard_descendants
  11: sc_state_db::noncanonical::NonCanonicalOverlay<BlockHash,Key>::apply_pending
  12: sc_state_db::StateDb<BlockHash,Key>::apply_pending
  13: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::commit_operation
  14: <sc_service::client::client::Client<B,E,Block,RA> as sc_client_api::backend::LockImportRun<Block,B>>::lock_import_and_run
  15: sc_finality_grandpa::environment::finalize_block
  16: <sc_finality_grandpa::environment::Environment<B,Block,C,N,SC,VR> as finality_grandpa::voter::Environment<<Block as sp_runtime::traits::Block>::Hash,<<Block as sp_runtime::traits::Block>::Header as sp_runtime::traits::Header>::Number>>::finalize_block
  17: <finality_grandpa::voter::Voter<H,N,E,GlobalIn,GlobalOut> as core::future::future::Future>::poll
  18: <finality_grandpa::voter::Voter<H,N,E,GlobalIn,GlobalOut> as core::future::future::Future>::poll
  19: <sc_finality_grandpa::VoterWork<B,Block,C,N,SC,VR> as core::future::future::Future>::poll
  20: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  21: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  22: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  23: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  24: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  25: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: std::thread::local::LocalKey<T>::with
  28: tokio::park::thread::CachedParkThread::block_on
  29: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  30: tokio::runtime::task::harness::Harness<T,S>::poll
  31: tokio::runtime::blocking::pool::Inner::run
  32: std::sys_common::backtrace::__rust_begin_short_backtrace
  33: core::ops::function::FnOnce::call_once{{vtable.shim}}
  34: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys/unix/thread.rs:106:17
  35: start_thread
  36: clone


Thread 'tokio-runtime-worker' panicked at 'there is a parent entry for each entry in levels; qed', /github/home/.cargo/git/checkouts/substrate-a7fa553ead635512/5cb17b4/client/state-db/src/noncanonical.rs:150

This is a bug. Please report it at:

        https://github.com/darwinia-network/darwinia/issues/new
```

**Comment by AurevoirXavier** [comment]
Reopen if happens again.
